stages:
  - build
  - release

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script: echo "Zipping up files..."
  after_script: echo "BUILD_JOB_ID=$CI_JOB_ID" >> build.env
  artifacts:
    name: 'YouLikedIt $CI_COMMIT_TAG'
    paths:
      - css
      - js
      - manifest.json
      - icon.png
    reports:
      dotenv: build.env
    expire_in: never

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  dependencies:
    - build
  script:
    - echo "Releasing (BUILD_JOB_ID=$BUILD_JOB_ID)..."
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'YouLikedIt $CI_COMMIT_TAG.zip'
          url: '$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$BUILD_JOB_ID/artifacts/download'
